openapi: "3.0.1"
info:
  description: "the backend server"
  version: "1.0.0"
  title: "backend server"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "backend"
  description: "Everything about the backend"
paths:
  /greeting:
    post:
      tags:
      - "backend"
      summary: "post a new greeting"
      operationId: "addGreeting"
      requestBody:
        description: "the greeting"
        required: true
        content:
          application/vnd.simon.openapi.demo.greeting.v1+json:
            schema:
              $ref: "#/components/schemas/Greeting"
      responses:
        200:
          description: "greeting has been posted"
components:
  schemas:
    Greeting:
      type: "object"
      properties:
        text:
          type: "string"